//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class taked_request
    {
        public int taked_request_id { get; set; }
        public int request_id { get; set; }
        public int master_id { get; set; }
    
        public virtual request request { get; set; }
        public virtual User User { get; set; }
    }
}
